import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const metadata = {

  title: {
      
      default: "Baku",
      template: "%s | Baku"
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <header className='bg-slate-700 text-5xl'>HEADER
        <Link className="text-2xl m-7 text-red-600" href="/">Home</Link>
        <Link className="text-2xl m-7 text-red-600" href="/blog">Blog</Link>
        <Link className="text-2xl m-7 text-red-600" href="/blog/cars">Cars</Link>
        <Link className="text-2xl m-7 text-red-600" href="/blog/buses">Buses</Link>
        <Link className="text-2xl m-7 text-red-600" href="/about">About</Link>
        </header>

        <main>{children}</main>

        <footer className='bg-red-600 text-5xl'>FOOTER</footer>

        </body>
    </html>
  )
}
